package com.konfigthis.client;

import com.konfigthis.client.api.ActivateControlAgreementForAccountApi;
import com.konfigthis.client.api.AdvanceReceivedPaymentApi;
import com.konfigthis.client.api.ApproveAuthorizationRequestApi;
import com.konfigthis.client.api.ApproveCheckPaymentApi;
import com.konfigthis.client.api.ArchiveCustomerApi;
import com.konfigthis.client.api.CancelApplicationApi;
import com.konfigthis.client.api.CancelCheckPaymentApi;
import com.konfigthis.client.api.CancelPaymentApi;
import com.konfigthis.client.api.CloseACardApi;
import com.konfigthis.client.api.CloseAnAccountApi;
import com.konfigthis.client.api.ConfirmCheckDepositApi;
import com.konfigthis.client.api.CreateAccountApi;
import com.konfigthis.client.api.CreateApplicationApi;
import com.konfigthis.client.api.CreateApplicationFormApi;
import com.konfigthis.client.api.CreateCheckDepositApi;
import com.konfigthis.client.api.CreateCheckPaymentApi;
import com.konfigthis.client.api.CreateCounterpartyApi;
import com.konfigthis.client.api.CreateCustomerTokenApi;
import com.konfigthis.client.api.CreateCustomerTokenVerificationApi;
import com.konfigthis.client.api.CreateFeeApi;
import com.konfigthis.client.api.CreateOrgApiTokenApi;
import com.konfigthis.client.api.CreateRecurringPaymentApi;
import com.konfigthis.client.api.CreateRewardApi;
import com.konfigthis.client.api.CreateWebhookApi;
import com.konfigthis.client.api.CreateACardApi;
import com.konfigthis.client.api.CreateADocumentForAnApplicationApi;
import com.konfigthis.client.api.CreateAPaymentApi;
import com.konfigthis.client.api.CreateARepaymentApi;
import com.konfigthis.client.api.DeactivateControlAgreementForAccountApi;
import com.konfigthis.client.api.DeclineAuthorizationRequestApi;
import com.konfigthis.client.api.DeleteCounterpartyApi;
import com.konfigthis.client.api.DisableRecurringPaymentApi;
import com.konfigthis.client.api.DisableWebhookApi;
import com.konfigthis.client.api.DownloadADocumentApi;
import com.konfigthis.client.api.DownloadADocumentBackSideApi;
import com.konfigthis.client.api.EnableRecurringPaymentApi;
import com.konfigthis.client.api.EnableWebhookApi;
import com.konfigthis.client.api.EnterControlAgreementForAccountApi;
import com.konfigthis.client.api.FireEventApi;
import com.konfigthis.client.api.FreezeACardApi;
import com.konfigthis.client.api.FreezeAnAccountApi;
import com.konfigthis.client.api.GetAtmLocationsListApi;
import com.konfigthis.client.api.GetAccountApi;
import com.konfigthis.client.api.GetAccountLimitsApi;
import com.konfigthis.client.api.GetApplicationApi;
import com.konfigthis.client.api.GetApplicationFormApi;
import com.konfigthis.client.api.GetAuthorizationApi;
import com.konfigthis.client.api.GetAuthorizationRequestApi;
import com.konfigthis.client.api.GetBankVerificationPdfApi;
import com.konfigthis.client.api.GetCardApi;
import com.konfigthis.client.api.GetCardLimitsApi;
import com.konfigthis.client.api.GetCardPinStatusApi;
import com.konfigthis.client.api.GetCheckDepositApi;
import com.konfigthis.client.api.GetCheckDepositBackImageApi;
import com.konfigthis.client.api.GetCheckDepositFrontImageApi;
import com.konfigthis.client.api.GetCheckPaymentApi;
import com.konfigthis.client.api.GetCounterpartyApi;
import com.konfigthis.client.api.GetCounterpartyBalanceApi;
import com.konfigthis.client.api.GetCustomerApi;
import com.konfigthis.client.api.GetDisputeApi;
import com.konfigthis.client.api.GetEventApi;
import com.konfigthis.client.api.GetInstitutionApi;
import com.konfigthis.client.api.GetListAccountsApi;
import com.konfigthis.client.api.GetListApplicationFormsApi;
import com.konfigthis.client.api.GetListApplicationsApi;
import com.konfigthis.client.api.GetListAuthorizationRequestsApi;
import com.konfigthis.client.api.GetListAuthorizationsApi;
import com.konfigthis.client.api.GetListCheckDepositsApi;
import com.konfigthis.client.api.GetListCheckPaymentsApi;
import com.konfigthis.client.api.GetListCounterpartiesApi;
import com.konfigthis.client.api.GetListCustomersApi;
import com.konfigthis.client.api.GetListDisputesApi;
import com.konfigthis.client.api.GetListEventsApi;
import com.konfigthis.client.api.GetListOrgApiTokensApi;
import com.konfigthis.client.api.GetListPaymentsApi;
import com.konfigthis.client.api.GetListRecurringPaymentsApi;
import com.konfigthis.client.api.GetListRepaymentsApi;
import com.konfigthis.client.api.GetListRewardsApi;
import com.konfigthis.client.api.GetListStatementsApi;
import com.konfigthis.client.api.GetListTransactionsApi;
import com.konfigthis.client.api.GetListWebhooksApi;
import com.konfigthis.client.api.GetListOfCardsApi;
import com.konfigthis.client.api.GetListOfDocumentsApi;
import com.konfigthis.client.api.GetPaymentApi;
import com.konfigthis.client.api.GetReceivedPaymentApi;
import com.konfigthis.client.api.GetReceivedPaymentsListApi;
import com.konfigthis.client.api.GetRecurringPaymentApi;
import com.konfigthis.client.api.GetRepaymentApi;
import com.konfigthis.client.api.GetRewardApi;
import com.konfigthis.client.api.GetStatementHtmlApi;
import com.konfigthis.client.api.GetStatementPdfApi;
import com.konfigthis.client.api.GetTransactionApi;
import com.konfigthis.client.api.GetWebhookApi;
import com.konfigthis.client.api.GetABackImageApi;
import com.konfigthis.client.api.GetAFrontImageApi;
import com.konfigthis.client.api.GetListAccountEndOfDayBalancesHistoryApi;
import com.konfigthis.client.api.ReopenAnAccountApi;
import com.konfigthis.client.api.ReportCardAsLostApi;
import com.konfigthis.client.api.ReportCardAsStolenApi;
import com.konfigthis.client.api.ReturnCheckPaymentApi;
import com.konfigthis.client.api.RevokeOrgApiTokenApi;
import com.konfigthis.client.api.StopPaymentApi;
import com.konfigthis.client.api.UnfreezeAccountApi;
import com.konfigthis.client.api.UnfreezeACardApi;
import com.konfigthis.client.api.UpdateAccountApi;
import com.konfigthis.client.api.UpdateApplicationApi;
import com.konfigthis.client.api.UpdateCardApi;
import com.konfigthis.client.api.UpdateCheckDepositApi;
import com.konfigthis.client.api.UpdateCounterpartyApi;
import com.konfigthis.client.api.UpdateCustomerApi;
import com.konfigthis.client.api.UpdatePaymentApi;
import com.konfigthis.client.api.UpdateReceivedPaymentApi;
import com.konfigthis.client.api.UpdateTransactionApi;
import com.konfigthis.client.api.UpdateWebhookApi;
import com.konfigthis.client.api.UploadAJpegDocumentForAnApplicationApi;
import com.konfigthis.client.api.UploadAJpegDocumentForAnApplicationBackSideApi;
import com.konfigthis.client.api.UploadAPngDocumentForAnApplicationApi;
import com.konfigthis.client.api.UploadAPngDocumentForAnApplicationBackSideApi;
import com.konfigthis.client.api.VerifyADocumentForAnApplicationApi;

public class Unit {
    private ApiClient apiClient;
    public final ActivateControlAgreementForAccountApi activateControlAgreementForAccount;
    public final AdvanceReceivedPaymentApi advanceReceivedPayment;
    public final ApproveAuthorizationRequestApi approveAuthorizationRequest;
    public final ApproveCheckPaymentApi approveCheckPayment;
    public final ArchiveCustomerApi archiveCustomer;
    public final CancelApplicationApi cancelApplication;
    public final CancelCheckPaymentApi cancelCheckPayment;
    public final CancelPaymentApi cancelPayment;
    public final CloseACardApi closeACard;
    public final CloseAnAccountApi closeAnAccount;
    public final ConfirmCheckDepositApi confirmCheckDeposit;
    public final CreateAccountApi createAccount;
    public final CreateApplicationApi createApplication;
    public final CreateApplicationFormApi createApplicationForm;
    public final CreateCheckDepositApi createCheckDeposit;
    public final CreateCheckPaymentApi createCheckPayment;
    public final CreateCounterpartyApi createCounterparty;
    public final CreateCustomerTokenApi createCustomerToken;
    public final CreateCustomerTokenVerificationApi createCustomerTokenVerification;
    public final CreateFeeApi createFee;
    public final CreateOrgApiTokenApi createOrgApiToken;
    public final CreateRecurringPaymentApi createRecurringPayment;
    public final CreateRewardApi createReward;
    public final CreateWebhookApi createWebhook;
    public final CreateACardApi createACard;
    public final CreateADocumentForAnApplicationApi createADocumentForAnApplication;
    public final CreateAPaymentApi createAPayment;
    public final CreateARepaymentApi createARepayment;
    public final DeactivateControlAgreementForAccountApi deactivateControlAgreementForAccount;
    public final DeclineAuthorizationRequestApi declineAuthorizationRequest;
    public final DeleteCounterpartyApi deleteCounterparty;
    public final DisableRecurringPaymentApi disableRecurringPayment;
    public final DisableWebhookApi disableWebhook;
    public final DownloadADocumentApi downloadADocument;
    public final DownloadADocumentBackSideApi downloadADocumentBackSide;
    public final EnableRecurringPaymentApi enableRecurringPayment;
    public final EnableWebhookApi enableWebhook;
    public final EnterControlAgreementForAccountApi enterControlAgreementForAccount;
    public final FireEventApi fireEvent;
    public final FreezeACardApi freezeACard;
    public final FreezeAnAccountApi freezeAnAccount;
    public final GetAtmLocationsListApi getAtmLocationsList;
    public final GetAccountApi getAccount;
    public final GetAccountLimitsApi getAccountLimits;
    public final GetApplicationApi getApplication;
    public final GetApplicationFormApi getApplicationForm;
    public final GetAuthorizationApi getAuthorization;
    public final GetAuthorizationRequestApi getAuthorizationRequest;
    public final GetBankVerificationPdfApi getBankVerificationPdf;
    public final GetCardApi getCard;
    public final GetCardLimitsApi getCardLimits;
    public final GetCardPinStatusApi getCardPinStatus;
    public final GetCheckDepositApi getCheckDeposit;
    public final GetCheckDepositBackImageApi getCheckDepositBackImage;
    public final GetCheckDepositFrontImageApi getCheckDepositFrontImage;
    public final GetCheckPaymentApi getCheckPayment;
    public final GetCounterpartyApi getCounterparty;
    public final GetCounterpartyBalanceApi getCounterpartyBalance;
    public final GetCustomerApi getCustomer;
    public final GetDisputeApi getDispute;
    public final GetEventApi getEvent;
    public final GetInstitutionApi getInstitution;
    public final GetListAccountsApi getListAccounts;
    public final GetListApplicationFormsApi getListApplicationForms;
    public final GetListApplicationsApi getListApplications;
    public final GetListAuthorizationRequestsApi getListAuthorizationRequests;
    public final GetListAuthorizationsApi getListAuthorizations;
    public final GetListCheckDepositsApi getListCheckDeposits;
    public final GetListCheckPaymentsApi getListCheckPayments;
    public final GetListCounterpartiesApi getListCounterparties;
    public final GetListCustomersApi getListCustomers;
    public final GetListDisputesApi getListDisputes;
    public final GetListEventsApi getListEvents;
    public final GetListOrgApiTokensApi getListOrgApiTokens;
    public final GetListPaymentsApi getListPayments;
    public final GetListRecurringPaymentsApi getListRecurringPayments;
    public final GetListRepaymentsApi getListRepayments;
    public final GetListRewardsApi getListRewards;
    public final GetListStatementsApi getListStatements;
    public final GetListTransactionsApi getListTransactions;
    public final GetListWebhooksApi getListWebhooks;
    public final GetListOfCardsApi getListOfCards;
    public final GetListOfDocumentsApi getListOfDocuments;
    public final GetPaymentApi getPayment;
    public final GetReceivedPaymentApi getReceivedPayment;
    public final GetReceivedPaymentsListApi getReceivedPaymentsList;
    public final GetRecurringPaymentApi getRecurringPayment;
    public final GetRepaymentApi getRepayment;
    public final GetRewardApi getReward;
    public final GetStatementHtmlApi getStatementHtml;
    public final GetStatementPdfApi getStatementPdf;
    public final GetTransactionApi getTransaction;
    public final GetWebhookApi getWebhook;
    public final GetABackImageApi getABackImage;
    public final GetAFrontImageApi getAFrontImage;
    public final GetListAccountEndOfDayBalancesHistoryApi getListAccountEndOfDayBalancesHistory;
    public final ReopenAnAccountApi reopenAnAccount;
    public final ReportCardAsLostApi reportCardAsLost;
    public final ReportCardAsStolenApi reportCardAsStolen;
    public final ReturnCheckPaymentApi returnCheckPayment;
    public final RevokeOrgApiTokenApi revokeOrgApiToken;
    public final StopPaymentApi stopPayment;
    public final UnfreezeAccountApi unfreezeAccount;
    public final UnfreezeACardApi unfreezeACard;
    public final UpdateAccountApi updateAccount;
    public final UpdateApplicationApi updateApplication;
    public final UpdateCardApi updateCard;
    public final UpdateCheckDepositApi updateCheckDeposit;
    public final UpdateCounterpartyApi updateCounterparty;
    public final UpdateCustomerApi updateCustomer;
    public final UpdatePaymentApi updatePayment;
    public final UpdateReceivedPaymentApi updateReceivedPayment;
    public final UpdateTransactionApi updateTransaction;
    public final UpdateWebhookApi updateWebhook;
    public final UploadAJpegDocumentForAnApplicationApi uploadAJpegDocumentForAnApplication;
    public final UploadAJpegDocumentForAnApplicationBackSideApi uploadAJpegDocumentForAnApplicationBackSide;
    public final UploadAPngDocumentForAnApplicationApi uploadAPngDocumentForAnApplication;
    public final UploadAPngDocumentForAnApplicationBackSideApi uploadAPngDocumentForAnApplicationBackSide;
    public final VerifyADocumentForAnApplicationApi verifyADocumentForAnApplication;

    public Unit() {
        this(null);
    }

    public Unit(Configuration configuration) {
        this.apiClient = new ApiClient(null, configuration);
        this.activateControlAgreementForAccount = new ActivateControlAgreementForAccountApi(this.apiClient);
        this.advanceReceivedPayment = new AdvanceReceivedPaymentApi(this.apiClient);
        this.approveAuthorizationRequest = new ApproveAuthorizationRequestApi(this.apiClient);
        this.approveCheckPayment = new ApproveCheckPaymentApi(this.apiClient);
        this.archiveCustomer = new ArchiveCustomerApi(this.apiClient);
        this.cancelApplication = new CancelApplicationApi(this.apiClient);
        this.cancelCheckPayment = new CancelCheckPaymentApi(this.apiClient);
        this.cancelPayment = new CancelPaymentApi(this.apiClient);
        this.closeACard = new CloseACardApi(this.apiClient);
        this.closeAnAccount = new CloseAnAccountApi(this.apiClient);
        this.confirmCheckDeposit = new ConfirmCheckDepositApi(this.apiClient);
        this.createAccount = new CreateAccountApi(this.apiClient);
        this.createApplication = new CreateApplicationApi(this.apiClient);
        this.createApplicationForm = new CreateApplicationFormApi(this.apiClient);
        this.createCheckDeposit = new CreateCheckDepositApi(this.apiClient);
        this.createCheckPayment = new CreateCheckPaymentApi(this.apiClient);
        this.createCounterparty = new CreateCounterpartyApi(this.apiClient);
        this.createCustomerToken = new CreateCustomerTokenApi(this.apiClient);
        this.createCustomerTokenVerification = new CreateCustomerTokenVerificationApi(this.apiClient);
        this.createFee = new CreateFeeApi(this.apiClient);
        this.createOrgApiToken = new CreateOrgApiTokenApi(this.apiClient);
        this.createRecurringPayment = new CreateRecurringPaymentApi(this.apiClient);
        this.createReward = new CreateRewardApi(this.apiClient);
        this.createWebhook = new CreateWebhookApi(this.apiClient);
        this.createACard = new CreateACardApi(this.apiClient);
        this.createADocumentForAnApplication = new CreateADocumentForAnApplicationApi(this.apiClient);
        this.createAPayment = new CreateAPaymentApi(this.apiClient);
        this.createARepayment = new CreateARepaymentApi(this.apiClient);
        this.deactivateControlAgreementForAccount = new DeactivateControlAgreementForAccountApi(this.apiClient);
        this.declineAuthorizationRequest = new DeclineAuthorizationRequestApi(this.apiClient);
        this.deleteCounterparty = new DeleteCounterpartyApi(this.apiClient);
        this.disableRecurringPayment = new DisableRecurringPaymentApi(this.apiClient);
        this.disableWebhook = new DisableWebhookApi(this.apiClient);
        this.downloadADocument = new DownloadADocumentApi(this.apiClient);
        this.downloadADocumentBackSide = new DownloadADocumentBackSideApi(this.apiClient);
        this.enableRecurringPayment = new EnableRecurringPaymentApi(this.apiClient);
        this.enableWebhook = new EnableWebhookApi(this.apiClient);
        this.enterControlAgreementForAccount = new EnterControlAgreementForAccountApi(this.apiClient);
        this.fireEvent = new FireEventApi(this.apiClient);
        this.freezeACard = new FreezeACardApi(this.apiClient);
        this.freezeAnAccount = new FreezeAnAccountApi(this.apiClient);
        this.getAtmLocationsList = new GetAtmLocationsListApi(this.apiClient);
        this.getAccount = new GetAccountApi(this.apiClient);
        this.getAccountLimits = new GetAccountLimitsApi(this.apiClient);
        this.getApplication = new GetApplicationApi(this.apiClient);
        this.getApplicationForm = new GetApplicationFormApi(this.apiClient);
        this.getAuthorization = new GetAuthorizationApi(this.apiClient);
        this.getAuthorizationRequest = new GetAuthorizationRequestApi(this.apiClient);
        this.getBankVerificationPdf = new GetBankVerificationPdfApi(this.apiClient);
        this.getCard = new GetCardApi(this.apiClient);
        this.getCardLimits = new GetCardLimitsApi(this.apiClient);
        this.getCardPinStatus = new GetCardPinStatusApi(this.apiClient);
        this.getCheckDeposit = new GetCheckDepositApi(this.apiClient);
        this.getCheckDepositBackImage = new GetCheckDepositBackImageApi(this.apiClient);
        this.getCheckDepositFrontImage = new GetCheckDepositFrontImageApi(this.apiClient);
        this.getCheckPayment = new GetCheckPaymentApi(this.apiClient);
        this.getCounterparty = new GetCounterpartyApi(this.apiClient);
        this.getCounterpartyBalance = new GetCounterpartyBalanceApi(this.apiClient);
        this.getCustomer = new GetCustomerApi(this.apiClient);
        this.getDispute = new GetDisputeApi(this.apiClient);
        this.getEvent = new GetEventApi(this.apiClient);
        this.getInstitution = new GetInstitutionApi(this.apiClient);
        this.getListAccounts = new GetListAccountsApi(this.apiClient);
        this.getListApplicationForms = new GetListApplicationFormsApi(this.apiClient);
        this.getListApplications = new GetListApplicationsApi(this.apiClient);
        this.getListAuthorizationRequests = new GetListAuthorizationRequestsApi(this.apiClient);
        this.getListAuthorizations = new GetListAuthorizationsApi(this.apiClient);
        this.getListCheckDeposits = new GetListCheckDepositsApi(this.apiClient);
        this.getListCheckPayments = new GetListCheckPaymentsApi(this.apiClient);
        this.getListCounterparties = new GetListCounterpartiesApi(this.apiClient);
        this.getListCustomers = new GetListCustomersApi(this.apiClient);
        this.getListDisputes = new GetListDisputesApi(this.apiClient);
        this.getListEvents = new GetListEventsApi(this.apiClient);
        this.getListOrgApiTokens = new GetListOrgApiTokensApi(this.apiClient);
        this.getListPayments = new GetListPaymentsApi(this.apiClient);
        this.getListRecurringPayments = new GetListRecurringPaymentsApi(this.apiClient);
        this.getListRepayments = new GetListRepaymentsApi(this.apiClient);
        this.getListRewards = new GetListRewardsApi(this.apiClient);
        this.getListStatements = new GetListStatementsApi(this.apiClient);
        this.getListTransactions = new GetListTransactionsApi(this.apiClient);
        this.getListWebhooks = new GetListWebhooksApi(this.apiClient);
        this.getListOfCards = new GetListOfCardsApi(this.apiClient);
        this.getListOfDocuments = new GetListOfDocumentsApi(this.apiClient);
        this.getPayment = new GetPaymentApi(this.apiClient);
        this.getReceivedPayment = new GetReceivedPaymentApi(this.apiClient);
        this.getReceivedPaymentsList = new GetReceivedPaymentsListApi(this.apiClient);
        this.getRecurringPayment = new GetRecurringPaymentApi(this.apiClient);
        this.getRepayment = new GetRepaymentApi(this.apiClient);
        this.getReward = new GetRewardApi(this.apiClient);
        this.getStatementHtml = new GetStatementHtmlApi(this.apiClient);
        this.getStatementPdf = new GetStatementPdfApi(this.apiClient);
        this.getTransaction = new GetTransactionApi(this.apiClient);
        this.getWebhook = new GetWebhookApi(this.apiClient);
        this.getABackImage = new GetABackImageApi(this.apiClient);
        this.getAFrontImage = new GetAFrontImageApi(this.apiClient);
        this.getListAccountEndOfDayBalancesHistory = new GetListAccountEndOfDayBalancesHistoryApi(this.apiClient);
        this.reopenAnAccount = new ReopenAnAccountApi(this.apiClient);
        this.reportCardAsLost = new ReportCardAsLostApi(this.apiClient);
        this.reportCardAsStolen = new ReportCardAsStolenApi(this.apiClient);
        this.returnCheckPayment = new ReturnCheckPaymentApi(this.apiClient);
        this.revokeOrgApiToken = new RevokeOrgApiTokenApi(this.apiClient);
        this.stopPayment = new StopPaymentApi(this.apiClient);
        this.unfreezeAccount = new UnfreezeAccountApi(this.apiClient);
        this.unfreezeACard = new UnfreezeACardApi(this.apiClient);
        this.updateAccount = new UpdateAccountApi(this.apiClient);
        this.updateApplication = new UpdateApplicationApi(this.apiClient);
        this.updateCard = new UpdateCardApi(this.apiClient);
        this.updateCheckDeposit = new UpdateCheckDepositApi(this.apiClient);
        this.updateCounterparty = new UpdateCounterpartyApi(this.apiClient);
        this.updateCustomer = new UpdateCustomerApi(this.apiClient);
        this.updatePayment = new UpdatePaymentApi(this.apiClient);
        this.updateReceivedPayment = new UpdateReceivedPaymentApi(this.apiClient);
        this.updateTransaction = new UpdateTransactionApi(this.apiClient);
        this.updateWebhook = new UpdateWebhookApi(this.apiClient);
        this.uploadAJpegDocumentForAnApplication = new UploadAJpegDocumentForAnApplicationApi(this.apiClient);
        this.uploadAJpegDocumentForAnApplicationBackSide = new UploadAJpegDocumentForAnApplicationBackSideApi(this.apiClient);
        this.uploadAPngDocumentForAnApplication = new UploadAPngDocumentForAnApplicationApi(this.apiClient);
        this.uploadAPngDocumentForAnApplicationBackSide = new UploadAPngDocumentForAnApplicationBackSideApi(this.apiClient);
        this.verifyADocumentForAnApplication = new VerifyADocumentForAnApplicationApi(this.apiClient);
    }

}
