/*
 * Unit OpenAPI specifications
 * An OpenAPI specifications for unit-sdk clients
 *
 * The version of the OpenAPI document: 0.0.2
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ApplicationFormPropertyAttributes
 */
public class ApplicationFormPropertyAttributesTest {
    private final ApplicationFormPropertyAttributes model = new ApplicationFormPropertyAttributes();

    /**
     * Model tests for ApplicationFormPropertyAttributes
     */
    @Test
    public void testApplicationFormPropertyAttributes() {
        // TODO: test ApplicationFormPropertyAttributes
    }

    /**
     * Test the property 'tags'
     */
    @Test
    public void tagsTest() {
        // TODO: test tags
    }

    /**
     * Test the property 'email'
     */
    @Test
    public void emailTest() {
        // TODO: test email
    }

    /**
     * Test the property 'url'
     */
    @Test
    public void urlTest() {
        // TODO: test url
    }

    /**
     * Test the property 'stage'
     */
    @Test
    public void stageTest() {
        // TODO: test stage
    }

    /**
     * Test the property 'applicantDetails'
     */
    @Test
    public void applicantDetailsTest() {
        // TODO: test applicantDetails
    }

    /**
     * Test the property 'settingsOverride'
     */
    @Test
    public void settingsOverrideTest() {
        // TODO: test settingsOverride
    }

    /**
     * Test the property 'allowedApplicationTypes'
     */
    @Test
    public void allowedApplicationTypesTest() {
        // TODO: test allowedApplicationTypes
    }

}
