/*
 * Unit OpenAPI specifications
 * An OpenAPI specifications for unit-sdk clients
 *
 * The version of the OpenAPI document: 0.0.2
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CheckPaymentResourceAttributesCounterparty
 */
public class CheckPaymentResourceAttributesCounterpartyTest {
    private final CheckPaymentResourceAttributesCounterparty model = new CheckPaymentResourceAttributesCounterparty();

    /**
     * Model tests for CheckPaymentResourceAttributesCounterparty
     */
    @Test
    public void testCheckPaymentResourceAttributesCounterparty() {
        // TODO: test CheckPaymentResourceAttributesCounterparty
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'address'
     */
    @Test
    public void addressTest() {
        // TODO: test address
    }

    /**
     * Test the property 'counterpartyMoved'
     */
    @Test
    public void counterpartyMovedTest() {
        // TODO: test counterpartyMoved
    }

}
