/*
 * Unit OpenAPI specifications
 * An OpenAPI specifications for unit-sdk clients
 *
 * The version of the OpenAPI document: 0.0.2
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CreateOrgApiTokenViaApiRequestDataAttributesResourcesInner
 */
public class CreateOrgApiTokenViaApiRequestDataAttributesResourcesInnerTest {
    private final CreateOrgApiTokenViaApiRequestDataAttributesResourcesInner model = new CreateOrgApiTokenViaApiRequestDataAttributesResourcesInner();

    /**
     * Model tests for CreateOrgApiTokenViaApiRequestDataAttributesResourcesInner
     */
    @Test
    public void testCreateOrgApiTokenViaApiRequestDataAttributesResourcesInner() {
        // TODO: test CreateOrgApiTokenViaApiRequestDataAttributesResourcesInner
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'ids'
     */
    @Test
    public void idsTest() {
        // TODO: test ids
    }

}
