/*
 * Unit OpenAPI specifications
 * An OpenAPI specifications for unit-sdk clients
 *
 * The version of the OpenAPI document: 0.0.2
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for FreezeAnAccountByIdRequestDataAttributes
 */
public class FreezeAnAccountByIdRequestDataAttributesTest {
    private final FreezeAnAccountByIdRequestDataAttributes model = new FreezeAnAccountByIdRequestDataAttributes();

    /**
     * Model tests for FreezeAnAccountByIdRequestDataAttributes
     */
    @Test
    public void testFreezeAnAccountByIdRequestDataAttributes() {
        // TODO: test FreezeAnAccountByIdRequestDataAttributes
    }

    /**
     * Test the property 'reason'
     */
    @Test
    public void reasonTest() {
        // TODO: test reason
    }

    /**
     * Test the property 'reasonText'
     */
    @Test
    public void reasonTextTest() {
        // TODO: test reasonText
    }

}
