/*
 * Unit OpenAPI specifications
 * An OpenAPI specifications for unit-sdk clients
 *
 * The version of the OpenAPI document: 0.0.2
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.GetAccountLimitsByIdResponseDataAttributesCardLimits;
import com.konfigthis.client.model.GetAccountLimitsByIdResponseDataAttributesCardTotalsDaily;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for GetAccountLimitsByIdResponseDataAttributesCard
 */
public class GetAccountLimitsByIdResponseDataAttributesCardTest {
    private final GetAccountLimitsByIdResponseDataAttributesCard model = new GetAccountLimitsByIdResponseDataAttributesCard();

    /**
     * Model tests for GetAccountLimitsByIdResponseDataAttributesCard
     */
    @Test
    public void testGetAccountLimitsByIdResponseDataAttributesCard() {
        // TODO: test GetAccountLimitsByIdResponseDataAttributesCard
    }

    /**
     * Test the property 'limits'
     */
    @Test
    public void limitsTest() {
        // TODO: test limits
    }

    /**
     * Test the property 'totalsDaily'
     */
    @Test
    public void totalsDailyTest() {
        // TODO: test totalsDaily
    }

}
