/*
 * Unit OpenAPI specifications
 * An OpenAPI specifications for unit-sdk clients
 *
 * The version of the OpenAPI document: 0.0.2
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for GetListAuthorizationsFromApiFilterParameter
 */
public class GetListAuthorizationsFromApiFilterParameterTest {
    private final GetListAuthorizationsFromApiFilterParameter model = new GetListAuthorizationsFromApiFilterParameter();

    /**
     * Model tests for GetListAuthorizationsFromApiFilterParameter
     */
    @Test
    public void testGetListAuthorizationsFromApiFilterParameter() {
        // TODO: test GetListAuthorizationsFromApiFilterParameter
    }

    /**
     * Test the property 'accountId'
     */
    @Test
    public void accountIdTest() {
        // TODO: test accountId
    }

    /**
     * Test the property 'accountType'
     */
    @Test
    public void accountTypeTest() {
        // TODO: test accountType
    }

    /**
     * Test the property 'customerId'
     */
    @Test
    public void customerIdTest() {
        // TODO: test customerId
    }

    /**
     * Test the property 'cardId'
     */
    @Test
    public void cardIdTest() {
        // TODO: test cardId
    }

    /**
     * Test the property 'includeNonAuthorized'
     */
    @Test
    public void includeNonAuthorizedTest() {
        // TODO: test includeNonAuthorized
    }

    /**
     * Test the property 'merchantCategoryCode'
     */
    @Test
    public void merchantCategoryCodeTest() {
        // TODO: test merchantCategoryCode
    }

    /**
     * Test the property 'since'
     */
    @Test
    public void sinceTest() {
        // TODO: test since
    }

    /**
     * Test the property 'until'
     */
    @Test
    public void untilTest() {
        // TODO: test until
    }

    /**
     * Test the property 'fromAmount'
     */
    @Test
    public void fromAmountTest() {
        // TODO: test fromAmount
    }

    /**
     * Test the property 'toAmount'
     */
    @Test
    public void toAmountTest() {
        // TODO: test toAmount
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

}
