/*
 * Unit OpenAPI specifications
 * An OpenAPI specifications for unit-sdk clients
 *
 * The version of the OpenAPI document: 0.0.2
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for GetListApplicationsFromApi200ResponseMetaPagination
 */
public class GetListApplicationsFromApi200ResponseMetaPaginationTest {
    private final GetListApplicationsFromApi200ResponseMetaPagination model = new GetListApplicationsFromApi200ResponseMetaPagination();

    /**
     * Model tests for GetListApplicationsFromApi200ResponseMetaPagination
     */
    @Test
    public void testGetListApplicationsFromApi200ResponseMetaPagination() {
        // TODO: test GetListApplicationsFromApi200ResponseMetaPagination
    }

    /**
     * Test the property 'limit'
     */
    @Test
    public void limitTest() {
        // TODO: test limit
    }

    /**
     * Test the property 'offset'
     */
    @Test
    public void offsetTest() {
        // TODO: test offset
    }

    /**
     * Test the property 'total'
     */
    @Test
    public void totalTest() {
        // TODO: test total
    }

}
