/*
 * Unit OpenAPI specifications
 * An OpenAPI specifications for unit-sdk clients
 *
 * The version of the OpenAPI document: 0.0.2
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.AtmLocationAttributesCoordinates;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * AtmLocationAttributes
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class AtmLocationAttributes {
  public static final String SERIALIZED_NAME_NETWORK = "network";
  @SerializedName(SERIALIZED_NAME_NETWORK)
  private String network;

  public static final String SERIALIZED_NAME_LOCATION_NAME = "locationName";
  @SerializedName(SERIALIZED_NAME_LOCATION_NAME)
  private String locationName;

  public static final String SERIALIZED_NAME_COORDINATES = "coordinates";
  @SerializedName(SERIALIZED_NAME_COORDINATES)
  private AtmLocationAttributesCoordinates coordinates;

  public static final String SERIALIZED_NAME_ADDRESS = "address";
  @SerializedName(SERIALIZED_NAME_ADDRESS)
  private Object address = null;

  public static final String SERIALIZED_NAME_DISTANCE = "distance";
  @SerializedName(SERIALIZED_NAME_DISTANCE)
  private Integer distance;

  public static final String SERIALIZED_NAME_SURCHARGE_FREE = "surchargeFree";
  @SerializedName(SERIALIZED_NAME_SURCHARGE_FREE)
  private Boolean surchargeFree;

  public static final String SERIALIZED_NAME_ACCEPT_DEPOSITS = "acceptDeposits";
  @SerializedName(SERIALIZED_NAME_ACCEPT_DEPOSITS)
  private Boolean acceptDeposits;

  public AtmLocationAttributes() {
  }

  public AtmLocationAttributes network(String network) {
    
    
    
    
    this.network = network;
    return this;
  }

   /**
   * Get network
   * @return network
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getNetwork() {
    return network;
  }


  public void setNetwork(String network) {
    
    
    
    this.network = network;
  }


  public AtmLocationAttributes locationName(String locationName) {
    
    
    
    
    this.locationName = locationName;
    return this;
  }

   /**
   * Get locationName
   * @return locationName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getLocationName() {
    return locationName;
  }


  public void setLocationName(String locationName) {
    
    
    
    this.locationName = locationName;
  }


  public AtmLocationAttributes coordinates(AtmLocationAttributesCoordinates coordinates) {
    
    
    
    
    this.coordinates = coordinates;
    return this;
  }

   /**
   * Get coordinates
   * @return coordinates
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public AtmLocationAttributesCoordinates getCoordinates() {
    return coordinates;
  }


  public void setCoordinates(AtmLocationAttributesCoordinates coordinates) {
    
    
    
    this.coordinates = coordinates;
  }


  public AtmLocationAttributes address(Object address) {
    
    
    
    
    this.address = address;
    return this;
  }

   /**
   * Get address
   * @return address
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Object getAddress() {
    return address;
  }


  public void setAddress(Object address) {
    
    
    
    this.address = address;
  }


  public AtmLocationAttributes distance(Integer distance) {
    
    
    
    
    this.distance = distance;
    return this;
  }

   /**
   * Get distance
   * @return distance
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getDistance() {
    return distance;
  }


  public void setDistance(Integer distance) {
    
    
    
    this.distance = distance;
  }


  public AtmLocationAttributes surchargeFree(Boolean surchargeFree) {
    
    
    
    
    this.surchargeFree = surchargeFree;
    return this;
  }

   /**
   * Get surchargeFree
   * @return surchargeFree
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getSurchargeFree() {
    return surchargeFree;
  }


  public void setSurchargeFree(Boolean surchargeFree) {
    
    
    
    this.surchargeFree = surchargeFree;
  }


  public AtmLocationAttributes acceptDeposits(Boolean acceptDeposits) {
    
    
    
    
    this.acceptDeposits = acceptDeposits;
    return this;
  }

   /**
   * Get acceptDeposits
   * @return acceptDeposits
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getAcceptDeposits() {
    return acceptDeposits;
  }


  public void setAcceptDeposits(Boolean acceptDeposits) {
    
    
    
    this.acceptDeposits = acceptDeposits;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the AtmLocationAttributes instance itself
   */
  public AtmLocationAttributes putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AtmLocationAttributes atmLocationAttributes = (AtmLocationAttributes) o;
    return Objects.equals(this.network, atmLocationAttributes.network) &&
        Objects.equals(this.locationName, atmLocationAttributes.locationName) &&
        Objects.equals(this.coordinates, atmLocationAttributes.coordinates) &&
        Objects.equals(this.address, atmLocationAttributes.address) &&
        Objects.equals(this.distance, atmLocationAttributes.distance) &&
        Objects.equals(this.surchargeFree, atmLocationAttributes.surchargeFree) &&
        Objects.equals(this.acceptDeposits, atmLocationAttributes.acceptDeposits)&&
        Objects.equals(this.additionalProperties, atmLocationAttributes.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(network, locationName, coordinates, address, distance, surchargeFree, acceptDeposits, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AtmLocationAttributes {\n");
    sb.append("    network: ").append(toIndentedString(network)).append("\n");
    sb.append("    locationName: ").append(toIndentedString(locationName)).append("\n");
    sb.append("    coordinates: ").append(toIndentedString(coordinates)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    distance: ").append(toIndentedString(distance)).append("\n");
    sb.append("    surchargeFree: ").append(toIndentedString(surchargeFree)).append("\n");
    sb.append("    acceptDeposits: ").append(toIndentedString(acceptDeposits)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("network");
    openapiFields.add("locationName");
    openapiFields.add("coordinates");
    openapiFields.add("address");
    openapiFields.add("distance");
    openapiFields.add("surchargeFree");
    openapiFields.add("acceptDeposits");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to AtmLocationAttributes
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!AtmLocationAttributes.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in AtmLocationAttributes is not found in the empty JSON string", AtmLocationAttributes.openapiRequiredFields.toString()));
        }
      }
      if ((jsonObj.get("network") != null && !jsonObj.get("network").isJsonNull()) && !jsonObj.get("network").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `network` to be a primitive type in the JSON string but got `%s`", jsonObj.get("network").toString()));
      }
      if ((jsonObj.get("locationName") != null && !jsonObj.get("locationName").isJsonNull()) && !jsonObj.get("locationName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `locationName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("locationName").toString()));
      }
      // validate the optional field `coordinates`
      if (jsonObj.get("coordinates") != null && !jsonObj.get("coordinates").isJsonNull()) {
        AtmLocationAttributesCoordinates.validateJsonObject(jsonObj.getAsJsonObject("coordinates"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!AtmLocationAttributes.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'AtmLocationAttributes' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<AtmLocationAttributes> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(AtmLocationAttributes.class));

       return (TypeAdapter<T>) new TypeAdapter<AtmLocationAttributes>() {
           @Override
           public void write(JsonWriter out, AtmLocationAttributes value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public AtmLocationAttributes read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             AtmLocationAttributes instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of AtmLocationAttributes given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of AtmLocationAttributes
  * @throws IOException if the JSON string is invalid with respect to AtmLocationAttributes
  */
  public static AtmLocationAttributes fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, AtmLocationAttributes.class);
  }

 /**
  * Convert an instance of AtmLocationAttributes to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

