/*
 * Unit OpenAPI specifications
 * An OpenAPI specifications for unit-sdk clients
 *
 * The version of the OpenAPI document: 0.0.2
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DeactivateControlAgreementForAccountApi
 */
@Disabled
public class DeactivateControlAgreementForAccountApiTest {

    private static DeactivateControlAgreementForAccountApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new DeactivateControlAgreementForAccountApi(apiClient);
    }

    /**
     * Deactivate Account Control Agreement by Id
     *
     * Deactivate Control Agreement for Account via API
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void byIdTest() throws ApiException {
        String accountId = null;
        Object response = api.byId(accountId)
                .execute();
        // TODO: test validations
    }

}
