/*
 * Unit OpenAPI specifications
 * An OpenAPI specifications for unit-sdk clients
 *
 * The version of the OpenAPI document: 0.0.2
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiCallback;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiResponse;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.Pair;
import com.konfigthis.client.ProgressRequestBody;
import com.konfigthis.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import com.konfigthis.client.model.CreateCustomerTokenViaApiRequest;
import com.konfigthis.client.model.CreateCustomerTokenViaApiRequestData;
import com.konfigthis.client.model.CreateCustomerTokenViaApiResponse;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.ws.rs.core.GenericType;

public class CreateCustomerTokenApiGenerated {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public CreateCustomerTokenApiGenerated() throws IllegalArgumentException {
        this(Configuration.getDefaultApiClient());
    }

    public CreateCustomerTokenApiGenerated(ApiClient apiClient) throws IllegalArgumentException {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    private okhttp3.Call viaApiCall(String customerId, CreateCustomerTokenViaApiRequest createCustomerTokenViaApiRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = createCustomerTokenViaApiRequest;

        // create path and map variables
        String localVarPath = "/customers/{customerId}/token"
            .replace("{" + "customerId" + "}", localVarApiClient.escapeString(customerId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/vnd.api+json; charset=utf-8"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/vnd.api+json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "bearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call viaApiValidateBeforeCall(String customerId, CreateCustomerTokenViaApiRequest createCustomerTokenViaApiRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'customerId' is set
        if (customerId == null) {
            throw new ApiException("Missing the required parameter 'customerId' when calling viaApi(Async)");
        }

        // verify the required parameter 'createCustomerTokenViaApiRequest' is set
        if (createCustomerTokenViaApiRequest == null) {
            throw new ApiException("Missing the required parameter 'createCustomerTokenViaApiRequest' when calling viaApi(Async)");
        }

        return viaApiCall(customerId, createCustomerTokenViaApiRequest, _callback);

    }


    private ApiResponse<CreateCustomerTokenViaApiResponse> viaApiWithHttpInfo(String customerId, CreateCustomerTokenViaApiRequest createCustomerTokenViaApiRequest) throws ApiException {
        okhttp3.Call localVarCall = viaApiValidateBeforeCall(customerId, createCustomerTokenViaApiRequest, null);
        Type localVarReturnType = new TypeToken<CreateCustomerTokenViaApiResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    private okhttp3.Call viaApiAsync(String customerId, CreateCustomerTokenViaApiRequest createCustomerTokenViaApiRequest, final ApiCallback<CreateCustomerTokenViaApiResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = viaApiValidateBeforeCall(customerId, createCustomerTokenViaApiRequest, _callback);
        Type localVarReturnType = new TypeToken<CreateCustomerTokenViaApiResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }

    public class ViaApiRequestBuilder {
        private final String customerId;
        private CreateCustomerTokenViaApiRequestData data;

        private ViaApiRequestBuilder(String customerId) {
            this.customerId = customerId;
        }

        /**
         * Set data
         * @param data  (optional)
         * @return ViaApiRequestBuilder
         */
        public ViaApiRequestBuilder data(CreateCustomerTokenViaApiRequestData data) {
            this.data = data;
            return this;
        }
        
        /**
         * Build call for viaApi
         * @param _callback ApiCallback API callback
         * @return Call to execute
         * @throws ApiException If fail to serialize the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 201 </td><td> Successful Response </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call buildCall(final ApiCallback _callback) throws ApiException {
            CreateCustomerTokenViaApiRequest createCustomerTokenViaApiRequest = buildBodyParams();
            return viaApiCall(customerId, createCustomerTokenViaApiRequest, _callback);
        }

        private CreateCustomerTokenViaApiRequest buildBodyParams() {
            CreateCustomerTokenViaApiRequest createCustomerTokenViaApiRequest = new CreateCustomerTokenViaApiRequest();
            createCustomerTokenViaApiRequest.data(this.data);
            return createCustomerTokenViaApiRequest;
        }

        /**
         * Execute viaApi request
         * @return CreateCustomerTokenViaApiResponse
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 201 </td><td> Successful Response </td><td>  -  </td></tr>
         </table>
         */
        public CreateCustomerTokenViaApiResponse execute() throws ApiException {
            CreateCustomerTokenViaApiRequest createCustomerTokenViaApiRequest = buildBodyParams();
            ApiResponse<CreateCustomerTokenViaApiResponse> localVarResp = viaApiWithHttpInfo(customerId, createCustomerTokenViaApiRequest);
            return localVarResp.getResponseBody();
        }

        /**
         * Execute viaApi request with HTTP info returned
         * @return ApiResponse&lt;CreateCustomerTokenViaApiResponse&gt;
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 201 </td><td> Successful Response </td><td>  -  </td></tr>
         </table>
         */
        public ApiResponse<CreateCustomerTokenViaApiResponse> executeWithHttpInfo() throws ApiException {
            CreateCustomerTokenViaApiRequest createCustomerTokenViaApiRequest = buildBodyParams();
            return viaApiWithHttpInfo(customerId, createCustomerTokenViaApiRequest);
        }

        /**
         * Execute viaApi request (asynchronously)
         * @param _callback The callback to be executed when the API call finishes
         * @return The request call
         * @throws ApiException If fail to process the API call, e.g. serializing the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 201 </td><td> Successful Response </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call executeAsync(final ApiCallback<CreateCustomerTokenViaApiResponse> _callback) throws ApiException {
            CreateCustomerTokenViaApiRequest createCustomerTokenViaApiRequest = buildBodyParams();
            return viaApiAsync(customerId, createCustomerTokenViaApiRequest, _callback);
        }
    }

    /**
     * Create Customer Token
     * Create a Customer Token via API 
     * @param customerId ID of the customer to create token for (required)
     * @param createCustomerTokenViaApiRequest Create Customer Token Request (required)
     * @return ViaApiRequestBuilder
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Successful Response </td><td>  -  </td></tr>
     </table>
     */
    public ViaApiRequestBuilder viaApi(String customerId) throws IllegalArgumentException {
        if (customerId == null) throw new IllegalArgumentException("\"customerId\" is required but got null");
            

        return new ViaApiRequestBuilder(customerId);
    }
}
