/*
 * Unit OpenAPI specifications
 * An OpenAPI specifications for unit-sdk clients
 *
 * The version of the OpenAPI document: 0.0.2
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiCallback;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiResponse;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.Pair;
import com.konfigthis.client.ProgressRequestBody;
import com.konfigthis.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import com.konfigthis.client.model.GetInstitutionByRoutingNumberResponse;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.ws.rs.core.GenericType;

public class GetInstitutionApiGenerated {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public GetInstitutionApiGenerated() throws IllegalArgumentException {
        this(Configuration.getDefaultApiClient());
    }

    public GetInstitutionApiGenerated(ApiClient apiClient) throws IllegalArgumentException {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    private okhttp3.Call byRoutingNumberCall(String routingNumber, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/institutions/{routingNumber}"
            .replace("{" + "routingNumber" + "}", localVarApiClient.escapeString(routingNumber.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/vnd.api+json; charset=utf-8"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "bearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call byRoutingNumberValidateBeforeCall(String routingNumber, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'routingNumber' is set
        if (routingNumber == null) {
            throw new ApiException("Missing the required parameter 'routingNumber' when calling byRoutingNumber(Async)");
        }

        return byRoutingNumberCall(routingNumber, _callback);

    }


    private ApiResponse<GetInstitutionByRoutingNumberResponse> byRoutingNumberWithHttpInfo(String routingNumber) throws ApiException {
        okhttp3.Call localVarCall = byRoutingNumberValidateBeforeCall(routingNumber, null);
        Type localVarReturnType = new TypeToken<GetInstitutionByRoutingNumberResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    private okhttp3.Call byRoutingNumberAsync(String routingNumber, final ApiCallback<GetInstitutionByRoutingNumberResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = byRoutingNumberValidateBeforeCall(routingNumber, _callback);
        Type localVarReturnType = new TypeToken<GetInstitutionByRoutingNumberResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }

    public class ByRoutingNumberRequestBuilder {
        private final String routingNumber;

        private ByRoutingNumberRequestBuilder(String routingNumber) {
            this.routingNumber = routingNumber;
        }

        /**
         * Build call for byRoutingNumber
         * @param _callback ApiCallback API callback
         * @return Call to execute
         * @throws ApiException If fail to serialize the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call buildCall(final ApiCallback _callback) throws ApiException {
            return byRoutingNumberCall(routingNumber, _callback);
        }


        /**
         * Execute byRoutingNumber request
         * @return GetInstitutionByRoutingNumberResponse
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
         </table>
         */
        public GetInstitutionByRoutingNumberResponse execute() throws ApiException {
            ApiResponse<GetInstitutionByRoutingNumberResponse> localVarResp = byRoutingNumberWithHttpInfo(routingNumber);
            return localVarResp.getResponseBody();
        }

        /**
         * Execute byRoutingNumber request with HTTP info returned
         * @return ApiResponse&lt;GetInstitutionByRoutingNumberResponse&gt;
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
         </table>
         */
        public ApiResponse<GetInstitutionByRoutingNumberResponse> executeWithHttpInfo() throws ApiException {
            return byRoutingNumberWithHttpInfo(routingNumber);
        }

        /**
         * Execute byRoutingNumber request (asynchronously)
         * @param _callback The callback to be executed when the API call finishes
         * @return The request call
         * @throws ApiException If fail to process the API call, e.g. serializing the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call executeAsync(final ApiCallback<GetInstitutionByRoutingNumberResponse> _callback) throws ApiException {
            return byRoutingNumberAsync(routingNumber, _callback);
        }
    }

    /**
     * Get Institution by Routing Number
     * Get an Institution from API 
     * @param routingNumber routingNumber of the institution to get (required)
     * @return ByRoutingNumberRequestBuilder
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
     </table>
     */
    public ByRoutingNumberRequestBuilder byRoutingNumber(String routingNumber) throws IllegalArgumentException {
        if (routingNumber == null) throw new IllegalArgumentException("\"routingNumber\" is required but got null");
            

        return new ByRoutingNumberRequestBuilder(routingNumber);
    }
}
