/*
 * Unit OpenAPI specifications
 * An OpenAPI specifications for unit-sdk clients
 *
 * The version of the OpenAPI document: 0.0.2
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiCallback;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiResponse;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.Pair;
import com.konfigthis.client.ProgressRequestBody;
import com.konfigthis.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import com.konfigthis.client.model.UpdateTransactionViaApiRequest;
import com.konfigthis.client.model.UpdateTransactionViaApiResponse;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.ws.rs.core.GenericType;

public class UpdateTransactionApiGenerated {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public UpdateTransactionApiGenerated() throws IllegalArgumentException {
        this(Configuration.getDefaultApiClient());
    }

    public UpdateTransactionApiGenerated(ApiClient apiClient) throws IllegalArgumentException {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    private okhttp3.Call viaApiCall(String accountId, String transactionId, UpdateTransactionViaApiRequest updateTransactionViaApiRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = updateTransactionViaApiRequest;

        // create path and map variables
        String localVarPath = "/accounts/{accountId}/transactions/{transactionId}"
            .replace("{" + "accountId" + "}", localVarApiClient.escapeString(accountId.toString()))
            .replace("{" + "transactionId" + "}", localVarApiClient.escapeString(transactionId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/vnd.api+json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/vnd.api+json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "bearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "PATCH", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call viaApiValidateBeforeCall(String accountId, String transactionId, UpdateTransactionViaApiRequest updateTransactionViaApiRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'accountId' is set
        if (accountId == null) {
            throw new ApiException("Missing the required parameter 'accountId' when calling viaApi(Async)");
        }

        // verify the required parameter 'transactionId' is set
        if (transactionId == null) {
            throw new ApiException("Missing the required parameter 'transactionId' when calling viaApi(Async)");
        }

        // verify the required parameter 'updateTransactionViaApiRequest' is set
        if (updateTransactionViaApiRequest == null) {
            throw new ApiException("Missing the required parameter 'updateTransactionViaApiRequest' when calling viaApi(Async)");
        }

        return viaApiCall(accountId, transactionId, updateTransactionViaApiRequest, _callback);

    }


    private ApiResponse<UpdateTransactionViaApiResponse> viaApiWithHttpInfo(String accountId, String transactionId, UpdateTransactionViaApiRequest updateTransactionViaApiRequest) throws ApiException {
        okhttp3.Call localVarCall = viaApiValidateBeforeCall(accountId, transactionId, updateTransactionViaApiRequest, null);
        Type localVarReturnType = new TypeToken<UpdateTransactionViaApiResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    private okhttp3.Call viaApiAsync(String accountId, String transactionId, UpdateTransactionViaApiRequest updateTransactionViaApiRequest, final ApiCallback<UpdateTransactionViaApiResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = viaApiValidateBeforeCall(accountId, transactionId, updateTransactionViaApiRequest, _callback);
        Type localVarReturnType = new TypeToken<UpdateTransactionViaApiResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }

    public class ViaApiRequestBuilder {
        private final Object data;
        private final String accountId;
        private final String transactionId;

        private ViaApiRequestBuilder(Object data, String accountId, String transactionId) {
            this.data = data;
            this.accountId = accountId;
            this.transactionId = transactionId;
        }

        /**
         * Build call for viaApi
         * @param _callback ApiCallback API callback
         * @return Call to execute
         * @throws ApiException If fail to serialize the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call buildCall(final ApiCallback _callback) throws ApiException {
            UpdateTransactionViaApiRequest updateTransactionViaApiRequest = buildBodyParams();
            return viaApiCall(accountId, transactionId, updateTransactionViaApiRequest, _callback);
        }

        private UpdateTransactionViaApiRequest buildBodyParams() {
            UpdateTransactionViaApiRequest updateTransactionViaApiRequest = new UpdateTransactionViaApiRequest();
            updateTransactionViaApiRequest.data(this.data);
            return updateTransactionViaApiRequest;
        }

        /**
         * Execute viaApi request
         * @return UpdateTransactionViaApiResponse
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
         </table>
         */
        public UpdateTransactionViaApiResponse execute() throws ApiException {
            UpdateTransactionViaApiRequest updateTransactionViaApiRequest = buildBodyParams();
            ApiResponse<UpdateTransactionViaApiResponse> localVarResp = viaApiWithHttpInfo(accountId, transactionId, updateTransactionViaApiRequest);
            return localVarResp.getResponseBody();
        }

        /**
         * Execute viaApi request with HTTP info returned
         * @return ApiResponse&lt;UpdateTransactionViaApiResponse&gt;
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
         </table>
         */
        public ApiResponse<UpdateTransactionViaApiResponse> executeWithHttpInfo() throws ApiException {
            UpdateTransactionViaApiRequest updateTransactionViaApiRequest = buildBodyParams();
            return viaApiWithHttpInfo(accountId, transactionId, updateTransactionViaApiRequest);
        }

        /**
         * Execute viaApi request (asynchronously)
         * @param _callback The callback to be executed when the API call finishes
         * @return The request call
         * @throws ApiException If fail to process the API call, e.g. serializing the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call executeAsync(final ApiCallback<UpdateTransactionViaApiResponse> _callback) throws ApiException {
            UpdateTransactionViaApiRequest updateTransactionViaApiRequest = buildBodyParams();
            return viaApiAsync(accountId, transactionId, updateTransactionViaApiRequest, _callback);
        }
    }

    /**
     * Update Transaction
     * Update a Transaction via API 
     * @param accountId ID of the account to update transaction from (required)
     * @param transactionId ID of the transaction to update (required)
     * @param updateTransactionViaApiRequest Update Transaction Request (required)
     * @return ViaApiRequestBuilder
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
     </table>
     */
    public ViaApiRequestBuilder viaApi(Object data, String accountId, String transactionId) throws IllegalArgumentException {
        
        if (accountId == null) throw new IllegalArgumentException("\"accountId\" is required but got null");
            

        if (transactionId == null) throw new IllegalArgumentException("\"transactionId\" is required but got null");
            

        return new ViaApiRequestBuilder(data, accountId, transactionId);
    }
}
