/*
 * Unit OpenAPI specifications
 * An OpenAPI specifications for unit-sdk clients
 *
 * The version of the OpenAPI document: 0.0.2
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiCallback;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiResponse;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.Pair;
import com.konfigthis.client.ProgressRequestBody;
import com.konfigthis.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import com.konfigthis.client.model.UpdateCounterpartyViaApiRequest;
import com.konfigthis.client.model.UpdateCounterpartyViaApiResponse;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.ws.rs.core.GenericType;

public class UpdateCounterpartyApiGenerated {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public UpdateCounterpartyApiGenerated() throws IllegalArgumentException {
        this(Configuration.getDefaultApiClient());
    }

    public UpdateCounterpartyApiGenerated(ApiClient apiClient) throws IllegalArgumentException {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    private okhttp3.Call viaApiCall(String counterpartyId, UpdateCounterpartyViaApiRequest updateCounterpartyViaApiRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = updateCounterpartyViaApiRequest;

        // create path and map variables
        String localVarPath = "/counterparties/{counterpartyId}"
            .replace("{" + "counterpartyId" + "}", localVarApiClient.escapeString(counterpartyId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/vnd.api+json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/vnd.api+json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "bearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "PATCH", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call viaApiValidateBeforeCall(String counterpartyId, UpdateCounterpartyViaApiRequest updateCounterpartyViaApiRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'counterpartyId' is set
        if (counterpartyId == null) {
            throw new ApiException("Missing the required parameter 'counterpartyId' when calling viaApi(Async)");
        }

        // verify the required parameter 'updateCounterpartyViaApiRequest' is set
        if (updateCounterpartyViaApiRequest == null) {
            throw new ApiException("Missing the required parameter 'updateCounterpartyViaApiRequest' when calling viaApi(Async)");
        }

        return viaApiCall(counterpartyId, updateCounterpartyViaApiRequest, _callback);

    }


    private ApiResponse<UpdateCounterpartyViaApiResponse> viaApiWithHttpInfo(String counterpartyId, UpdateCounterpartyViaApiRequest updateCounterpartyViaApiRequest) throws ApiException {
        okhttp3.Call localVarCall = viaApiValidateBeforeCall(counterpartyId, updateCounterpartyViaApiRequest, null);
        Type localVarReturnType = new TypeToken<UpdateCounterpartyViaApiResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    private okhttp3.Call viaApiAsync(String counterpartyId, UpdateCounterpartyViaApiRequest updateCounterpartyViaApiRequest, final ApiCallback<UpdateCounterpartyViaApiResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = viaApiValidateBeforeCall(counterpartyId, updateCounterpartyViaApiRequest, _callback);
        Type localVarReturnType = new TypeToken<UpdateCounterpartyViaApiResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }

    public class ViaApiRequestBuilder {
        private final Object data;
        private final String counterpartyId;

        private ViaApiRequestBuilder(Object data, String counterpartyId) {
            this.data = data;
            this.counterpartyId = counterpartyId;
        }

        /**
         * Build call for viaApi
         * @param _callback ApiCallback API callback
         * @return Call to execute
         * @throws ApiException If fail to serialize the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call buildCall(final ApiCallback _callback) throws ApiException {
            UpdateCounterpartyViaApiRequest updateCounterpartyViaApiRequest = buildBodyParams();
            return viaApiCall(counterpartyId, updateCounterpartyViaApiRequest, _callback);
        }

        private UpdateCounterpartyViaApiRequest buildBodyParams() {
            UpdateCounterpartyViaApiRequest updateCounterpartyViaApiRequest = new UpdateCounterpartyViaApiRequest();
            updateCounterpartyViaApiRequest.data(this.data);
            return updateCounterpartyViaApiRequest;
        }

        /**
         * Execute viaApi request
         * @return UpdateCounterpartyViaApiResponse
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
         </table>
         */
        public UpdateCounterpartyViaApiResponse execute() throws ApiException {
            UpdateCounterpartyViaApiRequest updateCounterpartyViaApiRequest = buildBodyParams();
            ApiResponse<UpdateCounterpartyViaApiResponse> localVarResp = viaApiWithHttpInfo(counterpartyId, updateCounterpartyViaApiRequest);
            return localVarResp.getResponseBody();
        }

        /**
         * Execute viaApi request with HTTP info returned
         * @return ApiResponse&lt;UpdateCounterpartyViaApiResponse&gt;
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
         </table>
         */
        public ApiResponse<UpdateCounterpartyViaApiResponse> executeWithHttpInfo() throws ApiException {
            UpdateCounterpartyViaApiRequest updateCounterpartyViaApiRequest = buildBodyParams();
            return viaApiWithHttpInfo(counterpartyId, updateCounterpartyViaApiRequest);
        }

        /**
         * Execute viaApi request (asynchronously)
         * @param _callback The callback to be executed when the API call finishes
         * @return The request call
         * @throws ApiException If fail to process the API call, e.g. serializing the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call executeAsync(final ApiCallback<UpdateCounterpartyViaApiResponse> _callback) throws ApiException {
            UpdateCounterpartyViaApiRequest updateCounterpartyViaApiRequest = buildBodyParams();
            return viaApiAsync(counterpartyId, updateCounterpartyViaApiRequest, _callback);
        }
    }

    /**
     * Update Counterparty
     * Update a Counterparty via API 
     * @param counterpartyId ID of the counterparty to update (required)
     * @param updateCounterpartyViaApiRequest Update Counterparty Request (required)
     * @return ViaApiRequestBuilder
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
     </table>
     */
    public ViaApiRequestBuilder viaApi(Object data, String counterpartyId) throws IllegalArgumentException {
        
        if (counterpartyId == null) throw new IllegalArgumentException("\"counterpartyId\" is required but got null");
            

        return new ViaApiRequestBuilder(data, counterpartyId);
    }
}
